app:
  fixture:
    tags: [ "contract/basic", "fill/basic" ]
  contract:
    enable-cleanup: true

spring:
  application:
    name: modulith-refactor-demo
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true