app:
  fixture:
    tags: [ "contract/basic", "fill/basic" ]

spring:
  application:
    name: modulith-refactor-demo
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: com.cocroachden.modulithrefactordemo.infrastructure.persistence.SingleFieldEmbeddableNamingStrategy
    show-sql: true